In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [2]:
plt.style.use('grayscale')
plt.rcParams['lines.linewidth'] = 1.5
dark_style = {
    'figure.facecolor': '#008080',  # #212946
    'axes.facecolor': '#008080',
    'savefig.facecolor': '#008080',
    'axes.grid': True,
    'axes.grid.which': 'both',
    'axes.spines.left': False,
    'axes.spines.right': False,
    'axes.spines.top': False,
    'axes.spines.bottom': False,
    'grid.color': '#000000',  #2A3459
    'grid.linewidth': '1',
    'text.color': '0.9',
    'axes.labelcolor': '0.9',
    'xtick.color': '0.9',
    'ytick.color': '0.9',
    'font.size': 12 }
plt.rcParams.update(dark_style)

from pylab import rcParams
rcParams['figure.figsize'] = (18, 7)

In [4]:
from pathlib import Path
import pandas as pd
data_dir = Path("../data/monthly_data.csv")
data = pd.read_csv(data_dir)
data.head()

        month  applied  matched  accepted  approved  realized  completed
0  2022-01-01        8        2         1         0         0          0
1  2022-02-01       11        1         0         0         0          0
2  2022-03-01       52       16         7         3         0          0
3  2022-04-01       89       13         4         2         0          0
4  2022-05-01      132       54        27        20         2          0

In [7]:
'''Prepare dataframe for NiXTLA's Holt-Winters TSA framework
It simply requires only 3 colums: unique_id, ds, y
    unique_id -> unique identifier for series
    ds -> datestamp, which is the month column in our case
    y -> I choose 'approved' since these are confirmed to go on exchange and have less zeros
'''

# Prepare copy of original dataframe
df = data[['month', 'applied']]
df.head()

        month  applied
0  2022-01-01        8
1  2022-02-01       11
2  2022-03-01       52
3  2022-04-01       89
4  2022-05-01      132

In [10]:
df['unique_id'] = 1
df.columns = ['ds', 'y', 'unique_id']
df.head()

           ds    y  unique_id
0  2022-01-01    8          1
1  2022-02-01   11          1
2  2022-03-01   52          1
3  2022-04-01   89          1
4  2022-05-01  132          1

In [12]:
df['ds'] = pd.to_datetime(df['ds'])
print(df.dtypes)

ds           datetime64[us]
y                     int64
unique_id             int64
dtype: object